# Generated by Django 4.2.2 on 2023-06-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
